### ISSUE TITLE
Error: Could not find or load main class fasdpd.FASDPD

### ISSUE THREAD

**Issue by lananh-ngn** [javieriserte/fas-dpd#13]
Hi developers,
Thank you for developing this tool. I am interested in using it but I am encountering this error while trying to run Run.bat in the example directory:
Error: Could not find or load main class fasdpd.FASDPD
Caused by: java.lang.ClassNotFoundException: fasdpd.FASDPD
Thank you in advance for your help.

**Comment by javieriserte** [comment]
Thank you for reporting this issue.
I need to update the example files. Hope i can do it today.

**Comment by javieriserte** [comment]
Should be fixed in #14

**Comment by javieriserte** [comment]
Please try the GUI version release (i just updated it)

https://github.com/javieriserte/fas-dpd/releases/tag/1.4.2

**Comment by lananh-ngn** [comment]
Hello,
the new gui version works well with the examples! Thank you a lot for your help!

I am sorry I have another question, I am trying to use it with my data (alignment of amino acid sequences from Clustal) but it does not want to open my files. Is there any way to resolve this problem?
Thank you in advance.

**Comment by lananh-ngn** [comment]
Hello,
I just tested it and it works well! Thank you a lot for your help!

**Comment by javieriserte** [comment]
Hello,
At the moment, it only reads fasta files.
You should convert your files to fasta and it should work.
